### ISSUE TITLE
Missing feature: download subs in two languages

### ISSUE THREAD

**Issue by Gryzounours** [Valyreon/Subloader#10]
Hello, 
I would like to be able to download subtitles in English and French. They should be named: movietitle.fr.srt and movietitle.en.srt.
Just like the Kodi subtitles plugin feature

Thanks

**Comment by Valyreon** [comment]
Hi, what should happen if a user downloads two subtitles of the same language? Should one file be overwritten, or should there be two files named _movietitle.en.srt_ and _movietitle(1).en.srt_ ?

**Comment by Gryzounours** [comment]
> Hi, what should happen if a user downloads two subtitles of the same language? Should one file be overwritten, or should there be two files named _movietitle.en.srt_ and _movietitle(1).en.srt_ ?

Good question, I believe one subtitle per language is enough in 90% of the cases
