### ISSUE TITLE
Suggestion: searching subtitles for multiple files

### ISSUE THREAD

**Issue by orbittwz** [Valyreon/Subloader#12]
Hey, first and foremost, **this program is quite amazing**, makes it so easy to find and get subtitles fast.
I wonder if said suggestion can be implemented to the program, either by:
1. drag and drop multiple files onto the window, and the program search and display the list of all the subtitles found for the files.
adding a filter option, to narrow down the list as we type on the go will be so helpful.
2. add an option to search by name in general, by string, not by filename...
for example - searching for "the king of queens" will display all subtitles for the show.
that can be a massive query and hard to display, so I'm guessing adding a 2nd sub-option, like "release specific name" will help this...
in that 2nd option, I could write either the episode number, or specific string to narrow down the search.

let me know what you think...
thanks!

**Comment by Valyreon** [comment]
Hello,
I'm really sorry for not replying to you sooner, had covid at the time of your comment then forgot about it, been busy.

Anyway, the first suggestion is more complex and goes beyond what I intended this program to do, but it is doable and I will consider implementing it.

And the second suggestion is okay and I think it will be straightforward. Will work on these when I get the time and let you know.

Thank you for your feedback, I really appreciate it.

**Comment by orbittwz** [comment]
Hey!
I wish you health first and foremost, this pandemic is awful :(
No problem, whenever you have time, it's OK by me.
Thanks!

**Comment by Valyreon** [comment]
Manual search functionality is now implemented with the 1.5.0 release.
Multiple file search and display is beyond the scope of this app and will remain that way for now.

#14
