### ISSUE TITLE
Such a good program!

### ISSUE THREAD

**Issue by orbittwz** [Valyreon/Subloader#13]
Hey, this is such a great program to have, I hope this will be maintained continuously 👍 💯

**Comment by orbittwz** [comment]
Issue? maybe, a suggestion, is to have the program recognize the user is loading a series of files with the same title, and suggest getting the whole batch of subtitles at once, instead of loading the files one by one...
the batch will be composed of the user choice, either by string to find in the sub name, or release...

**Comment by Valyreon** [comment]
I think this suggestion is pretty much the same as the first one in the other issue you opened, so I am going to close this and you can comment on the other issue if you have more specific functional requests. Thank you.
