### ISSUE TITLE
Love the program.  Would it be possible to add login to opensubtitles.org?

### ISSUE THREAD

**Issue by dexusno** [Valyreon/Subloader#16]
I love the simplicity of this wonderful little piece of software, but as a member of Opensubtitles, I would like the possibility to log in with my username and password in the app.  When downloading subtitles without logging in, you get ads for supporting opensubtitles in the top and bottom of the subtitle.  I already support opensubtitles.org, and as a member when logging in, you do not get the ads in the subtitles you download.

A possibility to add my username and password in the app, getting subtitles with no ads in them would be super!

Again, great software.  Thanks!

**Comment by Gryzounours** [comment]
Hello you might want to take a look at https://github.com/DrKain/subclean

**Comment by Valyreon** [comment]
Hi, I took my time but Subloader v1.6.0 now has a Login function and uses the new OpenSubtitles.com API since the old one will soon be deprecated.
