### ISSUE TITLE
[Feature Request] Portable

### ISSUE THREAD

**Issue by dtoxic47** [Valyreon/Subloader#18]
Could we get a portable version so that the configuration files are stored with the executable and can be used on a usb stick without the need for installation?

**Comment by Valyreon** [comment]
You can find the zip file with portable executable in the latest release.

**Comment by dtoxic47** [comment]
Yeap i am officially blind....thx

**Comment by Valyreon** [comment]
You are not blind, I implemented it yesterday and released :) .

**Comment by dtoxic47** [comment]
One more thing,when i run the app from "Start---RUN" the config settings are placed in My Documents and are read from there instead of app folder,just so you know,if that could be fixed awesome

**Comment by Valyreon** [comment]
Not sure what you mean from "start --- RUN"? Can I get a screenshot? You could create a new issue.

**Comment by dtoxic47** [comment]
By Start---Run i mean this https://www.digitalcitizen.life/wp-content/uploads/2022/08/windows_run-1.png

**Comment by Valyreon** [comment]
Just tried running the portable version and the normal one via Run and it works as expected for both... Not sure what happens on your system, maybe %AppData% env variable gets changed or something.

Unrelated to this, I am interested, does the app follow the system accent color correctly on your computer?

**Comment by dtoxic47** [comment]
Colors are ok,btw i forgot to mention i am on Windows 7 x64,so maybe that is the problem?
