### ISSUE TITLE
Add to Scoop

### ISSUE THREAD

**Issue by sbstn87** [Valyreon/Subloader#22]
Hi,

could you add Subloader to Scoop?

https://scoop.sh/

**Comment by Valyreon** [comment]
Hi, I didn't know about Scoop, loved it and started using it! Thanks for that.

So anyway, my app does not have enough stars (needs at least 100) to be added to the **extras** bucket but I set up the scoop installation and you should be able to install like this:

`scoop install https://raw.githubusercontent.com/Valyreon/Subloader/master/InstallerFiles/Scoop/subloader.json`

It will read the manifest directly from the repository and install, there is autoupdate done and everything. Let me know if this works for you.

**Comment by sbstn87** [comment]
Hi,

I have successfully installed it via Scoop. Thanks for creating the script.

Hopefully Subloader gets enough stars soon to be included in the extras bucket.
