### ISSUE TITLE
can't login: invalid username/password

### ISSUE THREAD

**Issue by nascentt** [Valyreon/Subloader#29]
creds work fine on the website, using username and not email address
using v161

**Comment by Valyreon** [comment]
Just to make sure, opensubtitles has two different sites, the **.org** and **.com** site. Only credentials from the **.com** site are valid for this app.

Apart from that, have you ever successfully logged in? Check the logs folder (Settings -> About -> Logs), attach any files you find there.

**Comment by nascentt** [comment]
Oops. I was indeed using the .org creds, didn't realise they were different sites/logins. Sorry.
