### ISSUE TITLE
can't download subs

### ISSUE THREAD

**Issue by nascentt** [Valyreon/Subloader#30]
double clicking subs, it states downloaded, but I cant find the downloaded sub anywhere.
the option download to subs folder is greyed out
v161

**Comment by Valyreon** [comment]
The option **_Download to Subs folder_** can only be **enabled** if **_Allow multiple downloads_** is **enabled**. If **_Allow multiple downloads_** is disabled, the file will be overwritten every time you download, it will only keep the latest file. Here are the docs for settings: [Subloader Settings Documentation](https://github.com/Valyreon/Subloader/wiki/Subloader-GUI-Settings)

If both of these are **disabled**, the downloaded file should be in the same folder as the video file with the same name but different extension.

Check again with a few different files. Also check if you have any error logs (Settings -> About -> Logs), these are available only on non-portable version. If you have any txt files in the opened Logs folder, attach them here.

**Comment by nascentt** [comment]
Sorry for the noise.
It looks like the subtitles were indeed in the folder with the movie.  For some reason windows explorer wasn't refreshing/updating.

> The option Download to Subs folder can only be enabled if Allow multiple downloads is enabled

This was useful information, thanks.  Could be useful to reference this in the app UI somehow (tooltip?)
