### ISSUE TITLE
Portuguese Brazilian ?

### ISSUE THREAD

**Issue by LeoKesler** [Valyreon/Subloader#6]
Hi,

When I search for Portuguese Brazilian, I get three "Portuguese". But there is no indication if it is pt-pt or pt-br (pob ? ) .

So there, is two issues:

1. Searching for portuguese shows three "portuguese" .
2. There is no indication if it is pt-pt (Porguese from Portugal)  or pt-br (brazilian portuguese) .

Thank you.

**Comment by LeoKesler** [comment]
Just to be clear, in Settings, when I  search for "portuguese" ,  there are three "portuguese" available to be selected.
There is no indication if one of them is brazilian portuguese.

**Comment by Valyreon** [comment]
The fix will be out soon. I copied the codes for all languages from OpenSubtitle site I think, so I didn't really go through them. I found 3 Portuguese added "por" -regular, "pob" -brazil, and "pom", which I have no idea what it is and couldn't find anything so I removed it.
