### ISSUE TITLE
Request for Search by Name enabled by default

### ISSUE THREAD

**Issue by LeoKesler** [Valyreon/Subloader#7]
Hi,

If possible, can you add an option to have the option "Search by Name" enabled by default ?

I understand it gets many wrong results, but if the name of the file is renamed (by example, using programs like Sonarr ), the program do not found any subtitle.

Thank you.

**Comment by Valyreon** [comment]
I will make the app save the state of the checkboxes in the settings file, and restore them on opening next time.

I just didn't understand the second part. Hash doesn't look at the name, it hashes the binary file content, or a part of it. I got the function from OpenSubtitles so I didn't really look into it but you can see it is reading the video file itself.

So if the file was renamed, Search by Name could be less accurate but not Search by Hash.

**Comment by LeoKesler** [comment]
Testing with many files  in my system, search by hash success is about 15%.  It is working, but it failing most of time.

So, I need to mark Search by Name to find the subtitles.
