### ISSUE TITLE
Linux distro

### ISSUE THREAD

**Issue by mbnoimi** [Valyreon/Subloader#8]
Hi,

Do you've any plan for creating binary distro for Linux users?

**Comment by Valyreon** [comment]
Hi,

I would like that, I was planning on moving to MAUI when .NET 6 is out, there was some talk about it working on Linux but I'm not sure it will.

Currently I can't create a binary for Linux since WPF UI is only for Windows. Someone could possibly run it on wine though.

**Comment by mbnoimi** [comment]
> Someone could possibly run it on wine though.

Installing .NET is a very complicated procedure in Wine. I think the best option right here is using mono; Do you've any experience with it (I'm not a fan of .NET based apps)?

**Comment by Valyreon** [comment]
Not really. This is not complicated to implement in other languages/frameworks, so feel free to use my project as reference.
